### ISSUE TITLE
Cannot get Module to work

### ISSUE THREAD

**Issue by StarLordRammi** [glitch452/MMM-CoinMarketCap#9]
Hi, I keep getting the following error when the software starts

```
[2020-05-24 21:39:10.656] [ERROR]  WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/config/config.js:95
                {
                ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at loadConfig (/home/pi/MagicMirror/js/app.js:69:12)
    at App.start (/home/pi/MagicMirror/js/app.js:210:3)
    at Object.<anonymous> (/home/pi/MagicMirror/js/electron.js:115:7)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
```

this is what i added to the config file
Line 84 to 95

	{
            module: 'MMM-CoinMarketCap',
            position: "bottom_center",
            header: "Cryptocurrencies",
            config: {
                apiKey: 'redacted',
                currencies: ['bitcoin', 'ethereum', 'beam', 'ravencoin', 'turtlecoin'],
                view: 'graphWithChanges',
                conversion: 'GBP',
            }
        },

**Comment by StarLordRammi** [comment]
it seems like adding it before the default news module breaks it. I added it after it and now its working

**Comment by glitch452** [comment]
Did you have a comma after the news module block? `},` or was the the news module ended with just a brace `}`, because it looks like that's what the error was saying `Unexpected token {`.  I.e. the `{` is unexpected because there needs to be a comma to separate the entries.

**Comment by StarLordRammi** [comment]
it was like this
```
{
        module: 'MMM-CoinMarketCap',
        position: "bottom_center",
        header: "Cryptocurrencies",
        config: {
            apiKey: 'redacted',
            currencies: ['bitcoin', 'ethereum', 'beam', 'ravencoin', 'turtlecoin'],
            view: 'graphWithChanges',
            conversion: 'GBP',
        }
    },

		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "BBC",
						url: "http://feeds.bbci.co.uk/news/rss.xml"
					}
},			
	],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
		
		},
```



which didn't work but adding the module at the end worked :/

**Comment by glitch452** [comment]
In the news feed module, It looks like the brackets are not properly nested (or there is just an extra close brace `}` after the feed entry).  That might have been the problem?

This should work...
```
{
    module: 'MMM-CoinMarketCap',
    position: "bottom_center",
    header: "Cryptocurrencies",
    config: {
        apiKey: 'redacted',
        currencies: ['bitcoin', 'ethereum', 'beam', 'ravencoin', 'turtlecoin'],
        view: 'graphWithChanges',
        conversion: 'GBP',
    }
},
{
    module: "newsfeed",
    position: "bottom_bar",
    config: {
        feeds: [
            {
                title: "BBC",
                url: "http://feeds.bbci.co.uk/news/rss.xml"
            }
        ],
        showSourceTitle: true,
        showPublishDate: true,
        broadcastNewsFeeds: true,
        broadcastNewsUpdates: true
    }
}
```
